changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking-change
    - title: New Features 🎉
      labels:
        - enhancement
    - title: Bugfixes 🪲
      labels:
        - bug
    - title: Documentation 📖
      labels:
        - documentation
    - title: Other Changes
      labels:
        - "*"
